##readFile = open('C:\Python34\README.txt','rt')
###readFile.read()
###print(readFile.read(20))
##print(readFile.tell())
###readFile.tell()
##text=readFile.read(30)
##print(text)
##if '3.4.0' in text:
##    print(3**3)
##print(readFile.readline())
##print(readFile.readline())
##print(readFile.readline())
##print(readFile.readline())
##print(readFile.readline())
##print(readFile.readline())
##print(readFile.readline())
##print(readFile.readline())
##print(readFile.readline())
##print(readFile.readline())
##print(readFile.readline())
##print(readFile.readline())
##print(readFile.readline())
##print(readFile.readline())
##print(readFile.readline())
##print(readFile.tell())
##readFile.close()

a=1
while (a<=10):
    outfile=open('c:\Python34\Programs\writefile.txt','wt')
    outfile.write("\nThis is a useful skill to have, programming")
    outfile.write("\nthis is the second line of the file now")
    outfile.write("\nthis is the third line of the file now")
    a=str(a)
    outfile.write('\n---------------------------------------')
    outfile.write('\nthis is'+ a +'times')
    outfile.write('\n---------------------------------------')
    print("This is writing it",a,"times")
    a=int(a)
    a=a+1
    outfile.close()
outfile=open('c:\Python34\Programs\writefile.txt','rt')
text=outfile.read()
print(text)
outfile.close()
